name: Build WAR Package and Deploy to EC2 Tomcat

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Deploy to EC2 Tomcat  # Deploy using Tomcat Manager: use your credentials in secrets
        env:
          TOMCAT_URL: ${{ secrets.TOMCAT_URL }}
          TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
          TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
        run: |
          set -e
          CONTEXT_PATH="/myapp"

          # Install curl
          sudo apt-get update && sudo apt-get install -y curl

          # Undeploy the existing application
          echo "Undeploying existing application..."
          curl -v --fail "$TOMCAT_URL/manager/text/undeploy?path=$CONTEXT_PATH" \
            --user "$TOMCAT_USER:$TOMCAT_PASSWORD" || echo "No existing deployment to undeploy"

          # Get the built WAR file
          WAR_FILE=$(ls target/*.war)
          if [ ! -f "$WAR_FILE" ]; then
            echo "WAR file not found. Build might have failed."
            exit 1
          fi
          echo "Deploying WAR file: $WAR_FILE"

          # Deploy the new WAR file
          curl -v --fail --upload-file "$WAR_FILE" \
            "$TOMCAT_URL/manager/text/deploy?path=$CONTEXT_PATH&update=true" \
            --user "$TOMCAT_USER:$TOMCAT_PASSWORD"

          # Validate deployment
          echo "Validating deployment..."
          curl -v --fail "$TOMCAT_URL$CONTEXT_PATH" || echo "Validation failed"
          echo "Deployment completed successfully."