# Deploy the WAR file to Tomcat on EC2
- name: Deploy to EC2 Tomcat
  env:
    EC2_USER: ${{ secrets.EC2_USER }}
    EC2_HOST: ${{ secrets.EC2_HOST }}
    PEM_KEY: ${{ secrets.PEM_KEY }}
  run: |
    # Save PEM key to a file
    echo "${{ secrets.PEM_KEY }}" > ec2-key.pem
    chmod 600 ec2-key.pem

    # Upload the WAR file to the EC2 instance
    scp -o StrictHostKeyChecking=no -i ec2-key.pem target/*.war $EC2_USER@$EC2_HOST:/tmp/

    # SSH into the EC2 instance to deploy the WAR
    ssh -o StrictHostKeyChecking=no -i ec2-key.pem $EC2_USER@$EC2_HOST << 'EOF'
      sudo mv /tmp/*.war /opt/tomcat/webapps/
      sudo systemctl restart tomcat
    EOF

    # Clean up the PEM key
    rm -f ec2-key.pem
