name: Build and Deploy to EC2 Tomcat

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build the WAR file
      - name: Build with Maven
        run: mvn clean package

      # Deploy WAR to EC2 Tomcat
      - name: Deploy to EC2 Tomcat 
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          PEM_KEY: ${{ secrets.PEM_KEY }}
        run: |
          # Save PEM key to a file
          echo "${{ secrets.PEM_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem

          # Add EC2 host to known_hosts
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

          # Upload the WAR file
          scp -i ec2-key.pem target/*.war $EC2_USER@$EC2_HOST:/tmp/

          # SSH into EC2 to deploy the WAR
          ssh -i ec2-key.pem $EC2_USER@$EC2_HOST << 'EOF'
            sudo mv /tmp/*.war /opt/tomcat/webapps/
            sudo systemctl restart tomcat
          EOF

          # Clean up the PEM key
          rm -f ec2-key.pem
