name: Build WAR Package and Deploy to Tomcat

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Deploy to EC2 Tomcat
        env:
          TOMCAT_URL: ${{ secrets.TOMCAT_URL }}  # URL of the Tomcat Manager:http://18.60.47.20:8080
          TOMCAT_USER: ${{ secrets.TOMCAT_USER }} # Tomcat Manager username:tirup
          TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }} # Tomcat Manager password:ullitirup@123
        run: |
          # Install curl if not present
          sudo apt-get update && sudo apt-get install -y curl

          # 1. Get WAR file
          WAR_FILE=$(ls target/*.war)
          
          # 2. Force redeploy with verbose output
          curl -v --fail --upload-file "$WAR_FILE" \
            "$TOMCAT_URL/manager/text/deploy?path=/myapp&update=true" \
            --user "$TOMCAT_USER:$TOMCAT_PASSWORD"
          
          # 3. Content verification
          curl -s "$TOMCAT_URL/myapp/" | grep -q "Hello New Version" || \
            (echo "Deployed content doesn't match!" && exit 1)