name: Manual Build and Deploy

on:
  workflow_dispatch:

jobs:
  manual-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload WAR to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          PEM_KEY: ${{ secrets.PEM_KEY }}
        run: |
          echo "${{ secrets.PEM_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
          scp -i ec2-key.pem target/*.war $EC2_USER@$EC2_HOST:/tmp/
          ssh -i ec2-key.pem $EC2_USER@$EC2_HOST << 'EOF'
            sudo mv /tmp/*.war /opt/tomcat/webapps/
            sudo systemctl restart tomcat
          EOF
          rm -f ec2-key.pem
